error: only evaluate argument once
In case the error macros are called directly on a function, make sure to evaluate
it precisely once.

Signed-off-by: Tom Gundersen <teg@jklm.no>